In [1]:
import pandas as pd
from pathlib import Path

In [2]:
df = pd.read_csv(r'D:\Instant AI\AI\Graduation Project\RetainAI\Data\WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df.shape

(7043, 21)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
print(
    df.select_dtypes(include="object")
      .apply(lambda col: col.str.strip().eq("").sum())
)

customerID           0
gender               0
Partner              0
Dependents           0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
TotalCharges        11
Churn                0
dtype: int64

C:\Users\mazen\AppData\Local\Temp\ipykernel_4620\3964656831.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object")

In [8]:
total_charges=pd.to_numeric(df["TotalCharges"], errors="coerce")

print("Invalid TotalCharges values:", total_charges.isnull().sum())

print(df.loc[
    total_charges.isna(),[
        "customerID", "TotalCharges", "tenure", "MonthlyCharges","Churn"
    ]
])

Invalid TotalCharges values: 11
      customerID TotalCharges  tenure  MonthlyCharges Churn
488   4472-LVYGI                    0           52.55    No
753   3115-CZMZD                    0           20.25    No
936   5709-LVOEQ                    0           80.85    No
1082  4367-NUYAO                    0           25.75    No
1340  1371-DWPAZ                    0           56.05    No
3331  7644-OMVMY                    0           19.85    No
3826  3213-VVOLG                    0           25.35    No
4380  2520-SGTTA                    0           20.00    No
5218  2923-ARZLG                    0           19.70    No
6670  4075-WKNIU                    0           73.35    No
6754  2775-SEFEE                    0           61.90    No

In [9]:
df["TotalCharges"]=pd.to_numeric(
    df["TotalCharges"].str.strip(),
    errors="coerce")

df.loc[
    df["TotalCharges"].isna() & (df["tenure"]==0),
    "TotalCharges"
]=0

print("Missing TotalCharges:", df["TotalCharges"].isna().sum())
print("Data type:", df["TotalCharges"].dtype)
print("Customers with tenure = 0:", (df["tenure"] == 0).sum())

df.loc[df["tenure"] == 0, ["tenure", "MonthlyCharges", "TotalCharges", "Churn"]].head(12)

Missing TotalCharges: 0
Data type: float64
Customers with tenure = 0: 11

      tenure  MonthlyCharges  TotalCharges Churn
488        0           52.55           0.0    No
753        0           20.25           0.0    No
936        0           80.85           0.0    No
1082       0           25.75           0.0    No
1340       0           56.05           0.0    No
3331       0           19.85           0.0    No
3826       0           25.35           0.0    No
4380       0           20.00           0.0    No
5218       0           19.70           0.0    No
6670       0           73.35           0.0    No
6754       0           61.90           0.0    No

In [10]:
churn_summary=(
    df["Churn"]
    .value_counts()
    .rename_axis("Churn")
    .to_frame("Customers")
)

churn_summary["Percentage"] = (
    churn_summary["Customers"] / len(df) * 100
).round(2)

churn_summary

       Customers  Percentage
Churn
No          5174       73.46
Yes         1869       26.54

In [11]:
assert df["TotalCharges"].notna().all()
assert df["Churn"].isin(["Yes", "No"]).all()
assert not df.duplicated().any()

print("Data inspection and cleaning completed successfully.")
print(f"Final shape: {df.shape}")

Data inspection and cleaning completed successfully.
Final shape: (7043, 21)

In [12]:
OUTPUT_PATH = Path("../data/processed/telco_clean.csv")

OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(OUTPUT_PATH, index=False)

print(f"Cleaned dataset saved to: {OUTPUT_PATH}")

Cleaned dataset saved to: ..\data\processed\telco_clean.csv